"""Listas embebidas por defecto para el modo memorable."""

DEFAULT_SANTOS: list[str] = [
    "San Miguel",
    "San Gabriel",
    "San Rafael",
    "San Uriel",
    "San Jofiel",
    "San Chamuel",
    "San Zadkiel",
    "San Raguel",
    "San Remiel",
    "San Sariel",
    "San Anael",
    "San Cassiel",
    "San Azrael",
    "San Haniel",
    "San Jeremiel",
    "San Raziel",
    "San Camael",
    "San Metatron",
    "San Sandalfon",
    "San Ariel",
]

DEFAULT_SENYAS: list[str] = [
    "Espada",
    "Escudo",
    "Lanza",
    "Arco",
    "Flecha",
    "Casco",
    "Armadura",
    "Estandarte",
    "Trompeta",
    "Pergamino",
    "Cáliz",
    "Báculo",
    "Corona",
    "Anillo",
    "Medallón",
    "Talismán",
    "Cetro",
    "Orbe",
    "Capa",
    "Sandalia",
]

DEFAULT_CONTRASENYAS: list[str] = [
    "Valor",
    "Honor",
    "Lealtad",
    "Coraje",
    "Fuerza",
    "Justicia",
    "Verdad",
    "Libertad",
    "Sabiduría",
    "Compasión",
    "Esperanza",
    "Fe",
    "Caridad",
    "Humildad",
    "Paciencia",
    "Templanza",
    "Prudencia",
    "Diligencia",
    "Gratitud",
    "Perseverancia",
]

